M11-212 Stocklevel and some localizations
neteleven/showcase-storefront pull request #56
Opened 2024-07-04 09:04 UTC by Salmakis

2024-07-04 14:08 UTC, SimonLudwigNeteleven approved these changes

2024-07-22 11:05 UTC, YoshiKanai requested changes

2024-07-22 11:05 UTC, YoshiKanai commented on src/pages/product/ProductDetailPage.js
> +  const stockLevel = availability['k' + product.id]?.stockLevel || 0
... availability?.['k' + ...
Please add ?. after 'availability' otherwise results undefined

2024-07-22 11:05 UTC, YoshiKanai commented on src/pages/product/ProductDetailPage.js
> +  const stockLevel = availability['k' + product.id]?.stockLevel || 0
same ?. after availability

2024-07-22 11:05 UTC, YoshiKanai commented on src/pages/product/ProductListContent.js
> +              stockLevel: availability['k' + item.id]?.stockLevel || 0,
... availability?.['k' ...

2024-07-22 11:56 UTC, YoshiKanai commented
is the cart showing availability correctly?

2024-08-09 07:47 UTC, merged